# The URL the site will be built for
base_url = "https://avid-rustacean.dev"
title = "The Avid Rustacean"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminimal"
generate_feeds = true
feed_filenames = ["rss.xml"]
author = "Tyler Bloom"
taxonomies = [
    { name = "tags" },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_theme = "gruvbox-dark"
highlight_code = true
render_emoji = true

[extra]
accent_color = "orange"
# background_color = "auto"

logo_text = "avid-rustacean.dev"
author = "Tyler Bloom"
menu_items = [
    { name = "TUI", url = "$BASE_URL/tui" },
    { name = "About", url = "$BASE_URL/about" },
    { name = "Blog", url = "$BASE_URL" },
    { name = "Tags", url = "$BASE_URL/tags" },
    { name = "Projects", url = "$BASE_URL/projects" },
    { name = "GitHub", url = "https://github.com/TylerBloom", newtab = true },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/tyler-bloom-aba0a4156/", newtab = true },
    { name = "RSS", url = "$BASE_URL/rss.xml" },
]
